---
- name: Check folder
  stat:
    path: /var/lib/rancher/k3s
  register: k3s_varlib_dir

- name: Uninstall and wipe k3s
  ansible.builtin.shell: systemctl stop k3s.service; systemctl stop k3s-agent.service; /usr/local/bin/k3s-uninstall.sh; /usr/local/bin/k3s-agent-uninstall.sh ; rm -fr /var/lib/rancher /etc/rancher/k3s
  args:
    executable: /bin/bash
  when: k3s_varlib_dir.stat.exists
